# config.py
"""
MambaVSum Configuration
Hybrid Mamba-Transformer for Efficient Multimodal Video Summarization
"""
import torch


class Config:
    # ── Paths ────────────────────────────────────────────────
    data_dir        = "../data"
    dataset_name    = "tvsum"          # "tvsum" or "summe"

    datasets = {
        "tvsum":   "eccv16_dataset_tvsum_google_pool5.h5",
        "summe":   "eccv16_dataset_summe_google_pool5.h5",
    }

    # CLIP feature files (generated by extract_clip_features.py)
    clip_datasets = {
        "tvsum":   "tvsum_clip_features.h5",
        "summe":   "summe_clip_features.h5",
    }

    # ── Feature Dimensions ───────────────────────────────────
    # GoogLeNet pool5 (original ECCV16 features)
    googlenet_dim   = 1024

    # CLIP ViT-L/14 features
    clip_dim        = 768

    # Audio features (VGGish-style)
    audio_dim       = 128

    # Fused multimodal dimension
    fused_dim       = 256

    # ── Feature Mode ─────────────────────────────────────────
    # "googlenet"   : use original 1024-d features (backward compat)
    # "clip"        : use CLIP 768-d features only
    # "multimodal"  : fuse CLIP visual + audio features
    feature_mode    = "multimodal"

    # ── Mamba SSM Parameters ─────────────────────────────────
    # Tuned for RTX 3050 (4 GB VRAM) — increase for bigger GPUs
    mamba_d_model   = 128            # Internal model dimension
    mamba_d_state   = 8              # SSM state expansion factor
    mamba_d_conv    = 4              # Local convolution width
    mamba_expand    = 1              # Block expansion factor
    mamba_n_layers  = 2              # Number of BiMamba layers
    mamba_dropout   = 0.1

    # ── Multi-Scale Temporal Pooling ─────────────────────────
    temporal_scales = [1, 2, 4]      # Pooling strides for multi-scale

    # ── Scorer Head ──────────────────────────────────────────
    scorer_hidden   = 128
    scorer_dropout  = 0.3

    # ── Training ─────────────────────────────────────────────
    lr              = 1e-4
    weight_decay    = 1e-5
    epochs          = 30
    n_splits        = 5
    seed            = 12345

    # Scheduler
    use_scheduler   = True
    warmup_epochs   = 5

    # Gradient clipping
    clip_grad_norm  = 5.0

    # Early stopping
    patience        = 50

    # Evaluation
    eval_every      = 2
    summary_rate    = 0.15

    # ── GPU Settings ─────────────────────────────────────────
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    use_amp = torch.cuda.is_available()
    empty_cache_every_n_epochs = 50

    # ── Checkpoints ──────────────────────────────────────────
    checkpoint_dir  = "./checkpoints"
    results_file    = "./results.txt"

    # ── CLIP Feature Extraction ──────────────────────────────
    clip_model_name = "ViT-L/14"
    clip_batch_size = 64
    video_dir       = "./video"     # Raw video files for CLIP extraction

    @property
    def input_dim(self):
        """Return the input feature dimension based on feature_mode."""
        if self.feature_mode == "googlenet":
            return self.googlenet_dim
        elif self.feature_mode == "clip":
            return self.clip_dim
        elif self.feature_mode == "multimodal":
            return self.fused_dim
        else:
            raise ValueError(f"Unknown feature_mode: {self.feature_mode}")
